# Generated by Django 5.2.7 on 2025-10-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaSeguroFlorida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asegurado', models.CharField(max_length=120, verbose_name='Nombre del Asegurado')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección del Asegurado')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Asegurado')),
                ('aseguradora', models.CharField(max_length=150, verbose_name='Aseguradora')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='Número de Póliza')),
                ('numero_vin', models.CharField(max_length=30, verbose_name='Número VIN del Vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Vehículo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del Vehículo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año del Vehículo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Seguro')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de Expiración del Seguro')),
                ('direccion_oficina', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de la Oficina')),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la Oficina')),
                ('advertencia_legal', models.TextField(blank=True, null=True, verbose_name='Advertencia Legal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Tarjeta de Seguro de Florida',
                'verbose_name_plural': 'Tarjetas de Seguro de Florida',
                'db_table': 'tarjeta_seguro_florida',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
