# Generated by Django 5.2.7 on 2025-10-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaseguroflorida',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace al Documento'),
        ),
        migrations.AddField(
            model_name='tarjetaseguroflorida',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago Realizado'),
        ),
    ]
